In [1]:
import pandas as pd

In [42]:
df = pd.read_csv('all_cars.csv')
df = df.drop_duplicates()

In [43]:
df.head()

,posting_url,post_title,price,year_make_model,year,make,model,trim
0,https://austin.craigslist.org/cto/d/austin-201...,2015 HONDA Fit EX - White 23k miles,14000,2015 HONDA Fit,2015,honda,fit,EX - White 23k miles
1,https://austin.craigslist.org/cto/d/austin-201...,2010 Ford Fusion,1995,2010 Ford Fusion,2010,ford,fusion,NaN
2,https://austin.craigslist.org/cto/d/clyde-1986...,1986 Chevy Short Bed Step Side C10 w/AC,5000,1986 Chevy Short,1986,chevy,short,Bed Step Side C10 w/AC
3,https://austin.craigslist.org/cto/d/round-rock...,2004 Ford F150 fx4,8700,2004 Ford F150,2004,ford,f150,fx4
4,https://austin.craigslist.org/cto/d/dripping-s...,1999 Toyota 4Runner Limited 4WD,12000,1999 Toyota 4Runner,1999,toyota,4runner,Limited 4WD

In [44]:
df.make.value_counts().head(40)

ford            690
toyota          394
chevy           385
nissan          276
honda           258
dodge           247
chevrolet       236
jeep            188
gmc             146
bmw             132
hyundai          95
mercedes         81
lexus            80
ram              72
cadillac         72
kia              67
infiniti         51
subaru           49
mazda            49
lincoln          49
buick            48
chrysler         48
volkswagen       48
audi             43
mustang          43
acura            35
vw               33
f150             32
porsche          31
f250             30
mitsubishi       27
silverado        27
volvo            24
pontiac          23
jaguar           21
freightliner     21
tesla            20
mercury          20
range            19
scion            18
Name: make, dtype: int64

In [19]:
ford_fusions = df[(df.make == 'ford') & (df.model == 'fusion')]

In [20]:
df[df.make=='ford'].model.value_counts()

f             179
f150           78
expedition     53
focus          45
explorer       41
             ...
courier         1
hardtop         1
galaxie         1
4x4             1
1500            1
Name: model, Length: 69, dtype: int64

In [55]:
def all_makes(df):
    parent_dict = {}
    for makers in df.make.unique():
        parent_dict[makers] = {}
        
    return parent_dict

def all_models(df, parent_dict):
    for make, model_dict in parent_dict.items():
        for model in df[df.make == make].model.unique():
            model_dict[model] = {}
            
    return parent_dict

def all_years(df, parent_dict):
    for make, model_dict in parent_dict.items():
        for model, year_dict in model_dict.items():
            for year in df[(df.make ==make) & (df.model==model)].year.unique():
                year_dict[year] = {}
                
    return parent_dict

def all_prices(df, parent_dict):
    for make, model_dict in parent_dict.items():
        for model, year_dict in model_dict.items():
            for year, price_dict in year_dict.items():
                price_dict['avg_price'] = df[(df.make == make) & (df.model==model) & (df.year == year)].price.mean()
                price_dict['min_price'] = df[(df.make == make) & (df.model==model) & (df.year == year)].price.min()
                price_dict['max_price'] = df[(df.make == make) & (df.model==model) & (df.year == year)].price.max()
                price_dict['num_vehicles'] = df[(df.make==make)&(df.model==model)&(df.year==year)].price.size

    return parent_dict            
    
more_than_5_vehicles = []

    
parent = all_makes(df)
parent = all_models(df, parent)
parent = all_years(df, parent)
parent = all_prices(df, parent)


for make, model_dict in parent.items():
    for model, year_dict in model_dict.items():
        for year, price_dict in year_dict.items():
            if price_dict['num_vehicles'] > 5:
                more_than_5_vehicles.append({'make': make, 'model': model, 'year': year})

more_than_5_vehicles

[{'make': 'honda', 'model': 'accord', 'year': 2003},
 {'make': 'honda', 'model': 'accord', 'year': 2010},
 {'make': 'honda', 'model': 'accord', 'year': 2007},
 {'make': 'honda', 'model': 'accord', 'year': 2006},
 {'make': 'honda', 'model': 'accord', 'year': 2009},
 {'make': 'honda', 'model': 'civic', 'year': 2009},
 {'make': 'honda', 'model': 'civic', 'year': 2007},
 {'make': 'honda', 'model': 'odyssey', 'year': 2005},
 {'make': 'ford', 'model': 'fusion', 'year': 2014},
 {'make': 'ford', 'model': 'fusion', 'year': 2012},
 {'make': 'ford', 'model': 'f150', 'year': 2014},
 {'make': 'ford', 'model': 'f150', 'year': 2011},
 {'make': 'ford', 'model': 'f150', 'year': 2008},
 {'make': 'ford', 'model': 'expedition', 'year': 2006},
 {'make': 'ford', 'model': 'f', 'year': 1993},
 {'make': 'ford', 'model': 'f', 'year': 2013},
 {'make': 'ford', 'model': 'f', 'year': 2001},
 {'make': 'ford', 'model': 'f', 'year': 2010},
 {'make': 'ford', 'model': 'f', 'year': 2011},
 {'make': 'ford', 'model': 'f', 'year': 2014},
 {'make': 'ford', 'model': 'f', 'year': 2003},
 {'make': 'ford', 'model': 'f', 'year': 2005},
 {'make': 'ford', 'model': 'f', 'year': 2012},
 {'make': 'ford', 'model': 'f', 'year': 2002},
 {'make': 'ford', 'model': 'f', 'year': 2019},
 {'make': 'ford', 'model': 'f', 'year': 2008},
 {'make': 'ford', 'model': 'f', 'year': 2016},
 {'make': 'ford', 'model': 'f', 'year': 2007},
 {'make': 'ford', 'model': 'focus', 'year': 2013},
 {'make': 'ford', 'model': 'focus', 'year': 2014},
 {'make': 'ford', 'model': 'fairlane', 'year': 1957},
 {'make': 'chevy', 'model': 'silverado', 'year': 2007},
 {'make': 'chevy', 'model': 'silverado', 'year': 2018},
 {'make': 'chevy', 'model': 'silverado', 'year': 2008},
 {'make': 'chevy', 'model': 'silverado', 'year': 2004},
 {'make': 'chevy', 'model': 'tahoe', 'year': 2008},
 {'make': 'chevy', 'model': 'camaro', 'year': 1997},
 {'make': 'chevy', 'model': 'traverse', 'year': 2019},
 {'make': 'toyota', 'model': 'sienna', 'year': 2005},
 {'make': 'toyota', 'model': 'sienna', 'year': 2011},
 {'make': 'toyota', 'model': 'tundra', 'year': 2019},
 {'make': 'toyota', 'model': 'tundra', 'year': 2006},
 {'make': 'toyota', 'model': 'tundra', 'year': 2016},
 {'make': 'toyota', 'model': 'tundra', 'year': 2012},
 {'make': 'toyota', 'model': 'camry', 'year': 2007},
 {'make': 'toyota', 'model': 'camry', 'year': 2014},
 {'make': 'toyota', 'model': 'rav4', 'year': 2020},
 {'make': 'nissan', 'model': 'altima', 'year': 2012},
 {'make': 'nissan', 'model': 'altima', 'year': 2014},
 {'make': 'nissan', 'model': 'altima', 'year': 2011},
 {'make': 'nissan', 'model': 'altima', 'year': 2016},
 {'make': 'nissan', 'model': 'titan', 'year': 2006},
 {'make': 'clean', 'model': 'title', 'year': 2017},
 {'make': 'tesla', 'model': 'model', 'year': 2021},
 {'make': 'gmc', 'model': 'yukon', 'year': 2013},
 {'make': 'gmc', 'model': 'yukon', 'year': 2007},
 {'make': 'ram', 'model': '1500', 'year': 2019},
 {'make': 'ram', 'model': '2500', 'year': 2015},
 {'make': 'dodge', 'model': 'ram', 'year': 2004},
 {'make': 'dodge', 'model': 'ram', 'year': 2007},
 {'make': 'dodge', 'model': 'ram', 'year': 2012},
 {'make': 'dodge', 'model': 'ram', 'year': 2003},
 {'make': 'dodge', 'model': 'ram', 'year': 2001},
 {'make': 'dodge', 'model': 'ram', 'year': 2002},
 {'make': 'dodge', 'model': 'ram', 'year': 2005},
 {'make': 'dodge', 'model': 'ram', 'year': 2015},
 {'make': 'dodge', 'model': 'ram', 'year': 2008},
 {'make': 'dodge', 'model': 'charger', 'year': 2014},
 {'make': 'jeep', 'model': 'wrangler', 'year': 2008},
 {'make': 'jeep', 'model': 'wrangler', 'year': 2004},
 {'make': 'jeep', 'model': 'wrangler', 'year': 2013},
 {'make': 'kia', 'model': 'optima', 'year': 2020},
 {'make': 'hyundai', 'model': 'elantra', 'year': 2017},
 {'make': 'range', 'model': 'rover', 'year': 2008},
 {'make': 'lincoln', 'model': 'town', 'year': 2001},
 {'make': 'mazda', 'model': '3', 'year': 2006},
 {'make': 'fj', 'model': 'cruiser', 'year': 2012}]

In [56]:
def mk_mod_yr_df(item):
    return df[(df.make == item['make'])& (df.model == item['model'])&(df.year == item['year'])]
items = more_than_5_vehicles
mk_mod_yr_df(items[0])

,posting_url,post_title,price,year_make_model,year,make,model,trim
79,https://austin.craigslist.org/cto/d/georgetown...,2003 Honda Accord,6700,2003 Honda Accord,2003,honda,accord,NaN
272,https://austin.craigslist.org/cto/d/austin-200...,2003 Honda Accord LX 162K - CLEAN CARFAX - Gre...,4999,2003 Honda Accord,2003,honda,accord,LX 162K - CLEAN CARFAX - Great on Gas - AUX PORT
346,https://austin.craigslist.org/cto/d/leander-20...,2003 Honda Accord V6,6000,2003 Honda Accord,2003,honda,accord,V6
817,https://austin.craigslist.org/cto/d/austin-200...,2003 Honda Accord LX 162K - CLEAN CARFAX - Gre...,4999,2003 Honda Accord,2003,honda,accord,LX 162K - CLEAN CARFAX - Great on Gas - AUX PORT
2941,https://houston.craigslist.org/cto/d/friendswo...,2003 Honda Accord 3.0L V6,2500,2003 Honda Accord,2003,honda,accord,3.0L V6
5330,https://sanmarcos.craigslist.org/cto/d/san-mar...,2003 Honda Accord Sedan 170K Low Miles,2850,2003 Honda Accord,2003,honda,accord,Sedan 170K Low Miles

In [57]:
for i in items:
    print(mk_mod_yr_df(i))

                                            posting_url  \
79    https://austin.craigslist.org/cto/d/georgetown...
272   https://austin.craigslist.org/cto/d/austin-200...
346   https://austin.craigslist.org/cto/d/leander-20...
817   https://austin.craigslist.org/cto/d/austin-200...
2941  https://houston.craigslist.org/cto/d/friendswo...
5330  https://sanmarcos.craigslist.org/cto/d/san-mar...

                                             post_title  price  \
79                                    2003 Honda Accord   6700
272   2003 Honda Accord LX 162K - CLEAN CARFAX - Gre...   4999
346                                2003 Honda Accord V6   6000
817   2003 Honda Accord LX 162K - CLEAN CARFAX - Gre...   4999
2941                          2003 Honda Accord 3.0L V6   2500
5330             2003 Honda Accord Sedan 170K Low Miles   2850

        year_make_model  year   make   model  \
79    2003 Honda Accord  2003  honda  accord
272   2003 Honda Accord  2003  honda  accord
346   2003 Honda Accord  2003  honda  accord
817   2003 Honda Accord  2003  honda  accord
2941  2003 Honda Accord  2003  honda  accord
5330  2003 Honda Accord  2003  honda  accord

                                                   trim
79                                                  NaN
272    LX 162K - CLEAN CARFAX - Great on Gas - AUX PORT
346                                                  V6
817    LX 162K - CLEAN CARFAX - Great on Gas - AUX PORT
2941                                            3.0L V6
5330                               Sedan 170K Low Miles
                                            posting_url  \
131   https://austin.craigslist.org/cto/d/austin-201...
666   https://austin.craigslist.org/cto/d/austin-201...
674   https://austin.craigslist.org/cto/d/austin-201...
1029  https://austin.craigslist.org/cto/d/austin-201...
1322  https://austin.craigslist.org/cto/d/austin-201...
1489  https://collegestation.craigslist.org/cto/d/co...
2974  https://houston.craigslist.org/cto/d/conroe-be...
3329  https://houston.craigslist.org/cto/d/houston-2...
3553  https://houston.craigslist.org/cto/d/pasadena-...
3669  https://houston.craigslist.org/cto/d/spring-20...
3689  https://houston.craigslist.org/cto/d/houston-2...
4605  https://sanantonio.craigslist.org/cto/d/san-an...

                                             post_title  price  \
131   2010 Honda Accord EXL V6 172K - SUNROOF - Heat...   6999
666                        2010 Honda Accord Lx 1 owner  12000
674   2010 Honda Accord EXL V6 172K - SUNROOF - Heat...   6999
1029  2010 Honda Accord EXL V6 172K - SUNROOF - Heat...   6999
1322  2010 Honda Accord EXL V6 172K - SUNROOF - Heat...   6999
1489                               2010 HONDA ACCORD EX   9800
2974                Beautiful 2010 Honda Accord EX-L V6   5995
3329                 2010 HONDA ACCORD , EX-L 4CYLINDER   8495
3553                                  2010 Honda Accord   4000
3669                               2010 Honda Accord LX   8000
3689                 2010 HONDA ACCORD , EX-L 4CYLINDER   7995
4605                               2010 Honda Accord Ex   4000

        year_make_model  year   make   model  \
131   2010 Honda Accord  2010  honda  accord
666   2010 Honda Accord  2010  honda  accord
674   2010 Honda Accord  2010  honda  accord
1029  2010 Honda Accord  2010  honda  accord
1322  2010 Honda Accord  2010  honda  accord
1489  2010 HONDA ACCORD  2010  honda  accord
2974  2010 Honda Accord  2010  honda  accord
3329  2010 HONDA ACCORD  2010  honda  accord
3553  2010 Honda Accord  2010  honda  accord
3669  2010 Honda Accord  2010  honda  accord
3689  2010 HONDA ACCORD  2010  honda  accord
4605  2010 Honda Accord  2010  honda  accord

                                                   trim
131    EXL V6 172K - SUNROOF - Heated Seats - BLUETOOTH
666                                          Lx 1 owner
674    EXL V6 172K - SUNROOF - Heated Seats - BLUETOOTH
1029   EXL V6 172K - SUNROOF - Heated Seats - BLUETOOTH
1322   EXL V6 172K - SUNROOF - Heated Seats - BLUETOOTH
1489                                                 EX
2974                                            EX-L V6
3329                                   , EX-L 4CYLINDER
3553                                                NaN
3669                                                 LX
3689                                   , EX-L 4CYLINDER
4605                                                 Ex
                                            posting_url  \
133   https://austin.craigslist.org/cto/d/buda-2007-...
1897  https://houston.craigslist.org/cto/d/galveston...
2954  https://houston.craigslist.org/cto/d/houston-2...
3108  https://houston.craigslist.org/cto/d/houston-2...
3761  https://houston.craigslist.org/cto/d/houston-2...
4047  https://houston.craigslist.org/cto/d/houston-2...

                             post_title  price    year_make_model  year  \
133      2007 HONDA ACCORD - BAD ENGINE   1900  2007 HONDA ACCORD  2007
1897               2007 Honda Accord v6   2000  2007 Honda Accord  2007
2954  2007 Honda Accord  priced to sell   2900  2007 Honda Accord  2007
3108               2007 honda accord ex   5600  2007 honda accord  2007
3761     2007 HONDA ACCORD SEDAN MANUAL   4700  2007 HONDA ACCORD  2007
4047                  2007 honda accord   4700  2007 honda accord  2007

       make   model              trim
133   honda  accord      - BAD ENGINE
1897  honda  accord                v6
2954  honda  accord    priced to sell
3108  honda  accord                ex
3761  honda  accord      SEDAN MANUAL
4047  honda  accord               NaN
                                            posting_url  \
322   https://austin.craigslist.org/cto/d/austin-200...
1307  https://austin.craigslist.org/cto/d/leander-20...
1327  https://austin.craigslist.org/cto/d/austin-200...
2822  https://houston.craigslist.org/cto/d/katy-2006...
3200  https://houston.craigslist.org/cto/d/houston-2...
3771  https://houston.craigslist.org/cto/d/houston-2...
4776  https://sanantonio.craigslist.org/cto/d/san-an...

                                             post_title  price  \
322                                   2006 Honda Accord   5000
1307       2006 Honda Accord runs excellent!! Gas saver   4400
1327     2006 Honda Accord V6 excellent condition $6500   6500
2822                   2006 Honda Accord LX Sedan 4D V6   3750
3200                               2006 Honda Accord V6   2650
3771                               2006 Honda Accord V6   2650
4776  2006 HONDA ACCORD EXL 135,211 MILES NEW TIRES ...   4999

        year_make_model  year   make   model  \
322   2006 Honda Accord  2006  honda  accord
1307  2006 Honda Accord  2006  honda  accord
1327  2006 Honda Accord  2006  honda  accord
2822  2006 Honda Accord  2006  honda  accord
3200  2006 Honda Accord  2006  honda  accord
3771  2006 Honda Accord  2006  honda  accord
4776  2006 HONDA ACCORD  2006  honda  accord

                                                   trim
322                                                 NaN
1307                         runs excellent!! Gas saver
1327                       V6 excellent condition $6500
2822                                     LX Sedan 4D V6
3200                                                 V6
3771                                                 V6
4776   EXL 135,211 MILES NEW TIRES LEATHER SUNROOF C...
                                            posting_url  \
724   https://austin.craigslist.org/cto/d/austin-200...
1557  https://houston.craigslist.org/cto/d/houston-2...
2175  https://houston.craigslist.org/cto/d/houston-2...
2305  https://houston.craigslist.org/cto/d/houston-2...
3526  https://houston.craigslist.org/cto/d/houston-2...
3885  https://houston.craigslist.org/cto/d/houston-2...
4354  https://sanantonio.craigslist.org/cto/d/san-an...
4457  https://sanantonio.craigslist.org/cto/d/san-an...
5029  https://sanantonio.craigslist.org/cto/d/la-ver...

                   post_title  price    year_make_model  year   make   model  \
724         2009 Honda Accord   8000  2009 Honda Accord  2009  honda  accord
1557  2009 Honda Accord Coupe   6295  2009 Honda Accord  2009  honda  accord
2175  2009 Honda Accord Coupe   6495  2009 Honda Accord  2009  honda  accord
2305        2009 Honda Accord   5800  2009 Honda Accord  2009  honda  accord
3526  2009 Honda Accord Coupe   6495  2009 Honda Accord  2009  honda  accord
3885  2009 Honda Accord Coupe   6495  2009 Honda Accord  2009  honda  accord
4354     2009 Honda Accord Ex   7950  2009 Honda Accord  2009  honda  accord
4457     2009 Honda accord Ex   7499  2009 Honda accord  2009  honda  accord
5029        2009 Honda Accord   6000  2009 Honda Accord  2009  honda  accord

        trim
724      NaN
1557   Coupe
2175   Coupe
2305     NaN
3526   Coupe
3885   Coupe
4354      Ex
4457      Ex
5029     NaN
                                            posting_url  \
92    https://austin.craigslist.org/cto/d/austin-200...
122   https://austin.craigslist.org/cto/d/austin-200...
308   https://austin.craigslist.org/cto/d/kyle-2009-...
1591  https://houston.craigslist.org/cto/d/humble-20...
2406  https://houston.craigslist.org/cto/d/houston-2...
2436  https://houston.craigslist.org/cto/d/katy-2009...
3253  https://houston.craigslist.org/cto/d/humble-20...
3285  https://houston.craigslist.org/cto/d/katy-2009...
3425  https://houston.craigslist.org/cto/d/houston-2...

                          post_title  price   year_make_model  year   make  \
92                  2009 Honda Civic   2500  2009 Honda Civic  2009  honda
122      2009 Honda Civic 113k Miles   7800  2009 Honda Civic  2009  honda
308            2009 Honda Civic LX-S   6500  2009 Honda Civic  2009  honda
1591  2009 Honda Civic Ex lousiana t   4500  2009 Honda Civic  2009  honda
2406             2009 Honda Civic EX   6800  2009 Honda Civic  2009  honda
2436                2009 Honda Civic   4900  2009 Honda Civic  2009  honda
3253  2009 Honda Civic Ex lousiana t   4500  2009 Honda Civic  2009  honda
3285                2009 Honda Civic   4900  2009 Honda Civic  2009  honda
3425             2009 HONDA CIVIC LX   2700  2009 HONDA CIVIC  2009  honda

      model            trim
92    civic             NaN
122   civic      113k Miles
308   civic            LX-S
1591  civic   Ex lousiana t
2406  civic              EX
2436  civic             NaN
3253  civic   Ex lousiana t
3285  civic             NaN
3425  civic              LX
                                            posting_url  \
282   https://austin.craigslist.org/cto/d/austin-200...
429   https://austin.craigslist.org/cto/d/austin-200...
649   https://austin.craigslist.org/cto/d/austin-200...
1036  https://austin.craigslist.org/cto/d/austin-200...
1154  https://austin.craigslist.org/cto/d/austin-200...
1891  https://houston.craigslist.org/cto/d/conroe-20...
2592  https://houston.craigslist.org/cto/d/houston-2...
3354  https://houston.craigslist.org/cto/d/houston-2...

                                             post_title  price  \
282   2007 Honda Civic LX 181K - GAS SAVER - Only On...   5499
429                                 2007 HONDA CIVIC LX   7000
649   2007 Honda Civic LX 181K - GAS SAVER - Only On...   5499
1036  2007 Honda Civic LX 181K - GAS SAVER - Only On...   5499
1154  2007 Honda Civic LX 181K - GAS SAVER - Only On...   5499
1891                                   2007 Honda Civic   3495
2592                       2007 Honda Civic EX like new   8000
3354                       2007 Honda Civic EX like new   8000

       year_make_model  year   make  model  \
282   2007 Honda Civic  2007  honda  civic
429   2007 HONDA CIVIC  2007  honda  civic
649   2007 Honda Civic  2007  honda  civic
1036  2007 Honda Civic  2007  honda  civic
1154  2007 Honda Civic  2007  honda  civic
1891  2007 Honda Civic  2007  honda  civic
2592  2007 Honda Civic  2007  honda  civic
3354  2007 Honda Civic  2007  honda  civic

                                                   trim
282    LX 181K - GAS SAVER - Only One Owner - CLEAN ...
429                                                  LX
649    LX 181K - GAS SAVER - Only One Owner - CLEAN ...
1036   LX 181K - GAS SAVER - Only One Owner - CLEAN ...
1154   LX 181K - GAS SAVER - Only One Owner - CLEAN ...
1891                                                NaN
2592                                        EX like new
3354                                        EX like new
                                            posting_url  \
86    https://austin.craigslist.org/cto/d/austin-200...
267   https://austin.craigslist.org/cto/d/austin-200...
663   https://austin.craigslist.org/cto/d/austin-200...
871   https://austin.craigslist.org/cto/d/austin-200...
1037  https://austin.craigslist.org/cto/d/austin-200...
1136  https://austin.craigslist.org/cto/d/austin-200...
1650  https://corpuschristi.craigslist.org/cto/d/aus...
2403  https://houston.craigslist.org/cto/d/richmond-...
4575  https://sanantonio.craigslist.org/cto/d/austin...
5415  https://victoriatx.craigslist.org/cto/d/austin...

                                             post_title  price  \
86                                   2005 Honda Odyssey   3399
267   2005 Honda Odyssey EXL 155K - SEATS 8 -Leather...   4999
663   2005 Honda Odyssey EXL 155K - SEATS 8 -Leather...   4999
871   2005 Honda Odyssey EXL 155K - SEATS 8 -Leather...   4999
1037                                 2005 Honda Odyssey   4995
1136  2005 Honda Odyssey EXL 155K - SEATS 8 -Leather...   4999
1650                                 2005 Honda Odyssey   3399
2403                                 2005 Honda Odyssey   4500
4575                                 2005 Honda Odyssey   3399
5415                                 2005 Honda Odyssey   3399

         year_make_model  year   make    model  \
86    2005 Honda Odyssey  2005  honda  odyssey
267   2005 Honda Odyssey  2005  honda  odyssey
663   2005 Honda Odyssey  2005  honda  odyssey
871   2005 Honda Odyssey  2005  honda  odyssey
1037  2005 Honda Odyssey  2005  honda  odyssey
1136  2005 Honda Odyssey  2005  honda  odyssey
1650  2005 Honda Odyssey  2005  honda  odyssey
2403  2005 Honda Odyssey  2005  honda  odyssey
4575  2005 Honda Odyssey  2005  honda  odyssey
5415  2005 Honda Odyssey  2005  honda  odyssey

                                                   trim
86                                                  NaN
267    EXL 155K - SEATS 8 -Leather Interior- CLEAN C...
663    EXL 155K - SEATS 8 -Leather Interior- CLEAN C...
871    EXL 155K - SEATS 8 -Leather Interior- CLEAN C...
1037                                                NaN
1136   EXL 155K - SEATS 8 -Leather Interior- CLEAN C...
1650                                                NaN
2403                                                NaN
4575                                                NaN
5415                                                NaN
                                            posting_url  \
188   https://austin.craigslist.org/cto/d/austin-201...
684   https://austin.craigslist.org/cto/d/austin-201...
898   https://austin.craigslist.org/cto/d/austin-201...
2981  https://houston.craigslist.org/cto/d/houston-2...
4872  https://sanantonio.craigslist.org/cto/d/san-an...
5038  https://sanantonio.craigslist.org/cto/d/san-an...

                     post_title  price   year_make_model  year  make   model  \
188            2014 Ford Fusion   6200  2014 Ford Fusion  2014  ford  fusion
684         2014 ford fusion se   6900  2014 ford fusion  2014  ford  fusion
898            2014 ford fusion   7600  2014 ford fusion  2014  ford  fusion
2981           2014 Ford Fusion   6500  2014 Ford Fusion  2014  ford  fusion
4872           2014 FORD FUSION   9950  2014 FORD FUSION  2014  ford  fusion
5038  2014 FORD FUSION TITANIUM   9500  2014 FORD FUSION  2014  ford  fusion

           trim
188         NaN
684          se
898         NaN
2981        NaN
4872        NaN
5038   TITANIUM
                                            posting_url  \
2121  https://houston.craigslist.org/cto/d/pasadena-...
2453  https://houston.craigslist.org/cto/d/pasadena-...
2681  https://houston.craigslist.org/cto/d/pasadena-...
3310  https://houston.craigslist.org/cto/d/houston-2...
3677  https://houston.craigslist.org/cto/d/houston-2...
4163  https://dallas.craigslist.org/dal/cto/d/dallas...
4501  https://sanantonio.craigslist.org/cto/d/cibolo...

                                             post_title  price  \
2121                                   2012 Ford Fusion   4100
2453                                   2012 Ford Fusion   4100
2681                                   2012 Ford Fusion   4500
3310  2012 Ford Fusion SE - 4cylinder - leather seat...   5795
3677  2012 Ford Fusion SE - 4cylinder - leather seat...   5799
4163                                   2012 ford fusion   4400
4501                                2012 Ford Fusion SE   4000

       year_make_model  year  make   model  \
2121  2012 Ford Fusion  2012  ford  fusion
2453  2012 Ford Fusion  2012  ford  fusion
2681  2012 Ford Fusion  2012  ford  fusion
3310  2012 Ford Fusion  2012  ford  fusion
3677  2012 Ford Fusion  2012  ford  fusion
4163  2012 ford fusion  2012  ford  fusion
4501  2012 Ford Fusion  2012  ford  fusion

                                               trim
2121                                            NaN
2453                                            NaN
2681                                            NaN
3310   SE - 4cylinder - leather seats - clean title
3677   SE - 4cylinder - leather seats - clean title
4163                                            NaN
4501                                             SE
                                            posting_url  \
576   https://austin.craigslist.org/cto/d/austin-201...
614   https://austin.craigslist.org/cto/d/del-valle-...
615   https://austin.craigslist.org/cto/d/del-valle-...
3000  https://houston.craigslist.org/cto/d/katy-2014...
4262  https://lubbock.craigslist.org/cto/d/slaton-20...
5128  https://sanantonio.craigslist.org/cto/d/san-an...

                                        post_title  price year_make_model  \
576             2014 Ford F150 XLT 8' Bed. AWESOME  19500  2014 Ford F150
614                        For sale 2014 ford f150  17500  2014 ford f150
615                        For sale 2014 ford f150  17500  2014 ford f150
3000                      2014 FORD F150 SUPER 3.7  17500  2014 FORD F150
4262           2014 Ford F150 XLT Extended Cab 4x4  12500  2014 Ford F150
5128  2014 Ford F150 original Tremor 4x4 low miles  32900  2014 Ford F150

      year  make model                            trim
576   2014  ford  f150             XLT 8' Bed. AWESOME
614   2014  ford  f150                             NaN
615   2014  ford  f150                             NaN
3000  2014  ford  f150                       SUPER 3.7
4262  2014  ford  f150            XLT Extended Cab 4x4
5128  2014  ford  f150   original Tremor 4x4 low miles
                                            posting_url  \
682   https://austin.craigslist.org/cto/d/austin-201...
1006  https://austin.craigslist.org/cto/d/austin-201...
1305  https://austin.craigslist.org/cto/d/buda-2011-...
1354  https://austin.craigslist.org/cto/d/austin-201...
2536  https://houston.craigslist.org/cto/d/humble-20...
2652  https://houston.craigslist.org/cto/d/houston-2...

                                 post_title  price year_make_model  year  \
682                  2011 ford f150 4x4 5.0   7900  2011 ford f150  2011
1006            2011 FORD F150 XLT CREW CAB   9300  2011 FORD F150  2011
1305            2011 Ford F150 Ecoboost 4x4  10000  2011 Ford F150  2011
1354  2011 Ford F150 XLT 4x4 4WD V6 w/Trubo  12500  2011 Ford F150  2011
2536                         2011 Ford F150  12500  2011 Ford F150  2011
2652                         2011 ford f150  11900  2011 ford f150  2011

      make model                     trim
682   ford  f150                  4x4 5.0
1006  ford  f150             XLT CREW CAB

In [17]:
ford_fusion_by_year[2010]

{'avg_price': 1995.0, 'min_price': 1995, 'max_price': 1995}

In [18]:
ford_fusion_by_year[2014]

{'avg_price': 7775.0, 'min_price': 6200, 'max_price': 9950}